### ISSUE TITLE
interpreter meta_data and EventMetaData broken

### ISSUE THREAD

**Issue by laborleben** [SiLab-Bonn/pyBAR_fei4_interpreter#1]
The bug leads to assigning wrong events for specific scan parameter combinations (e.g. pyBAR calibrate_hit_or).

More details:
Column **event_number** in **meta_data** table is always too small by one count (except for the first row where event_number is 0).

Column **stop_index** in **EventMetaData** table follows the Python slicing rules except for the last row in the **EventMetaData** table. The **stop_index** in the last row is too small by one count.

**Comment by laborleben** [comment]
It should be noted that the **index_stop** in the meta_data table of the raw data file follows the Python slicing rules (excluding index_stop). This convention should be carried out for all other files (interpreted data files).

**Comment by DavidLP** [comment]
This was the intention.

**Comment by laborleben** [comment]
sorry for the noise start_index of EventMetaData is OK. I updated the bug report.
