### ISSUE TITLE
Upload release 1.3.0 to pypi

### ISSUE THREAD

**Issue by laborleben** [SiLab-Bonn/pyBAR_fei4_interpreter#11]
Can you upload version 1.3.0 to pypi?

PS: or add me to package maintainer...

**Comment by DavidLP** [comment]
I cannot verify if the changes are not introducing regressions when pyBAR unit tests fail. Please fix them, then I can test and upload. I cannot blindly upload complex analysis code.

**Comment by DavidLP** [comment]
In view of the new release I added [two new unit tests to pyBAR](https://github.com/SiLab-Bonn/pyBAR/commit/7d3edfaeffa3380b272bab10465a63aeec938bca) to check trigger alignment and TDC analysis. These tests worked with interpreter version `1.2.1`. In pyBAR starting from [this commit](https://travis-ci.org/SiLab-Bonn/pyBAR/builds/200293831) the mess starts, unit tests fail etc. Before this is not fixed release is impossible.

**Comment by DavidLP** [comment]
@laborleben Please do not create releases that are not tested. That is bad coding.
