### ISSUE TITLE
meta_table should contain event_number_start and event_number_stop

### ISSUE THREAD

**Issue by laborleben** [SiLab-Bonn/pyBAR_fei4_interpreter#2]
Similar to the raw data meta_table, which contains index_start and index_stop, event meta_table should contain event_number_start and event_number_stop. The time stamp should be removed completely from this table and one row represents one scan parameter.

This would save a lot of space (one row per scan parameter and not per readout).
The time stamp information can be either recovered from the EventMetaData table together with the raw data file or by implementing another table which contains the time stamp start and stop per event.

**Comment by DavidLP** [comment]
I agree that we should have _event_number_start_ and _event_number_stop_.
But I do not see why we should change the meta_data table to have an entry per scan
parameter and not per readout. Space is not of concern with this table. Also one can now check
the meta_data before and after interpetation.

**Comment by laborleben** [comment]
I think we already agreed on that what you said. But it was not noted here :-)
I will check that again next week. It will be needed for the analysis of the beam test data.

**Comment by DavidLP** [comment]
Hehe ok :-). But why is it needed for the beam test data?
