### ISSUE TITLE
_EVENT_INCOMPLETE not set when trigger word immediately follows trigger word

### ISSUE THREAD

**Issue by laborleben** [SiLab-Bonn/pyBAR_fei4_interpreter#4]
Align at trigger is set to true and event builder should set _EVENT_INCOMPLETE when trigger word immediately follows trigger word.

**Comment by DavidLP** [comment]
That is not a bug. Event builing is solely relying on FE data!. The FE defines an event, this has nothing to do with the trigger number. All other kind of data (TLU, TDC) has special flags. Here for example it is the _more than one trigger number_ flag. Please do not set flags when something with the trigger number is wrong, that can happen too often. Why do you need this?

**Comment by DavidLP** [comment]
When I think about it, mmhh it might make sence to do it like this. Let's discuss tomorrow. In the past I did not force an align at  trigger number, but since this is now the case (when I remember correctly) this makes sence now.
