### ISSUE TITLE
Data format for trigger

### ISSUE THREAD

**Issue by DavidLP** [SiLab-Bonn/pyBAR_fei4_interpreter#5]
At the moment we use the 31 bit trigger data either as a time stamp or as a trigger number.
The Mimosa26 pyBAR readout produces trigger 15-bit time stamps in the high word and a 16-bit trigger
number in the low word.

I do not remember why we changed to 31 bit time stamp and I revert. Complain if you need this ;-)

**Comment by laborleben** [comment]
This will only work for the combined trigger data mode that we implemented 6 months ago for the telescope readout: https://github.com/SiLab-Bonn/basil/commit/6efe5ae90ed67bc1f99b62506bf614c4bfe908b5

The default trigger data format in pyBAR development is 0: https://github.com/SiLab-Bonn/pyBAR/blob/development/pybar/dut_configuration_mio.yaml#L19

So it is 31bit trigger number.

I guess we need to implement a switch for that.

**Comment by DavidLP** [comment]
Ahh good that you reminded me. Actually the telescope uses the combined mode right now, that was the reason why I changed it. And all unittests are still happy (because their data is older than 6 months....).
Do you need this for your data?

@YannickDieter Can you implement a switch?

**Comment by laborleben** [comment]
A switch would not be bad, otherwise I have to run with modified software or have my own branch.

**Comment by YannickDieter** [comment]
Of course I can implement a switch. What do you mean exactly with switch? Some if-statement which decides which data format for trigger should be used?

**Comment by DavidLP** [comment]
Yes some `if statement` in the code. Similar how a setting is set [here](https://github.com/SiLab-Bonn/pyBAR_fei4_interpreter/blob/master/pybar_fei4_interpreter/data_interpreter.pyx#L67) and used [here](https://github.com/SiLab-Bonn/pyBAR_fei4_interpreter/blob/master/pybar_fei4_interpreter/Interpret.cpp#L171) via:

```
  if (!_useTriggerTimeStamp)
    tTriggerNumber = TRIGGER_NUMBER_MACRO_NEW(tActualWord); // actual trigger number
  else
    tTriggerNumber = TRIGGER_TIME_STAMP_MACRO(tActualWord); // actual trigger number is a time stamp
```
You can actually substitute the function with a `set_trigger_format(type)` function. Where e.g.: 
 - type = 0: 15 bit time stamp + 16 bit trigger number
 - type = 1: 31 bit trigger number
 - type = 2: 31 bit time stamp.

**Comment by YannickDieter** [comment]
Switch is implemented, but cannot push the commit.

**Comment by DavidLP** [comment]
Can you create a pull request, then I will review and merge if it is ok?

**Comment by laborleben** [comment]
this is done.
