### ISSUE TITLE
pybar_fei4_interpreter/Basis.cpp (invalid) ifstream to int comparison

### ISSUE THREAD

**Issue by lmijovic** [SiLab-Bonn/pyBAR_fei4_interpreter#7]
Hello, 

in pybar_fei4_interpreter/Basis.cpp development and master (commit 682fc9c, used for testing), there is a comparison of ifstream to int, that will not compile in general (pip install $PWD/pyBAR_fei4_interpreter  | tee master.out)

	std::ifstream tFile(pFileName.c_str());
	return (tFile != 0);

Perhaps worth patching with one of basic_ios accessors (http://en.cppreference.com/w/cpp/io/ios_base/iostate)

cat patch.txt 
159,160c159
<       //return (tFile != 0);
<       return (tFile.good());
---
which should compile on any sistem (pip install $PWD/pyBAR_fei4_interpreter  | tee patch.out) ?

Thanks, 
Liza Mijovic

==

[patch.txt](https://github.com/SiLab-Bonn/pyBAR_fei4_interpreter/files/647193/patch.txt)

gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/6/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 6.2.0-5ubuntu12' --with-bugurl=file:///usr/share/doc/gcc-6/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-6 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-6-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-6-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-6-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 6.2.0 20161005 (Ubuntu 6.2.0-5ubuntu12)

**Comment by lmijovic** [comment]
sorry, overlooked that I cannot call the compilation outputs *.out. Renaming to .txt and re-attaching
[master.txt](https://github.com/SiLab-Bonn/pyBAR_fei4_interpreter/files/647202/master.txt)
[patch.txt](https://github.com/SiLab-Bonn/pyBAR_fei4_interpreter/files/647201/patch.txt)

**Comment by DavidLP** [comment]
Thank you for your bug report. It is a new C++11 feature that this comparison is now becomming invalid with the modern compilers. See [here](http://stackoverflow.com/questions/18619579/why-can-an-ifstream-object-be-compared-to-0). This function is nevertheless not needed and deleted now. Fix is in development.

**Comment by laborleben** [comment]
This needs to be added to development branch. Or was it by intention?
